### ISSUE TITLE
Error showing while training 

### ISSUE THREAD

**Issue by dasdristanta13** [paumarquez/mono2binaural-conv-tasnet#2]
While training it's giving error in train.py line number 182 as well as in data/custom_dataset_data_loader.py in line 50 `for i, data in enumerate(dataset):`. If you can help me!

**Comment by paumarquez** [comment]
Sorry Distranta, I forgot to reply.

Did you solve the issue? If not, could you show the error that it's raising?

**Comment by dasdristanta13** [comment]
Yes, I solved it. Thanks for the reply. I'm facing different issue now,
while training it's showing cuda error , no kernel image is available for
execution on the device. Is there any specific reason for such error? If
you can help me with that issue!
