### ISSUE TITLE
Error While Testing

### ISSUE THREAD

**Issue by dasdristanta13** [paumarquez/mono2binaural-conv-tasnet#3]
Hi, as far I understood that while testing the video frames also needs to be passed but I'm facing an issue. In the demo.py 
```
data = dataset.dataset.__getitem__(
                curr_audio_path,
                audio,
                audio_start_time=sliding_window_start / opt.audio_sampling_rate,
                audio_end_time=sliding_window_end / opt.audio_sampling_rate,
                audio_start=sliding_window_start,
                audio_end=sliding_window_end
            )
```
In this I'm getting the error
"TypeError: __getitem__() got an unexpected keyword argument 'audio_start_time''
.
If you can help me in this regard, it would be helpful.

**Comment by paumarquez** [comment]
Sorry for the delay.

What dataset are you loading? Send me the options that you are using to load the dataset and I might be able to help you.

Thanks

**Comment by dasdristanta13** [comment]
Thanks for the reply, actually in the mean time I resolved the issue. I actually loaded the dataset in different way, so this section was needed no more.
